import Foundation

struct PlanListSection: Identifiable {
    let date: Date
    let rows: [PlanListRowModel]
    let dailyIncomeTotal: Int
    let dailyExpenseTotal: Int

    var id: Date { date }
}

struct PlanListRowModel: Identifiable {
    let planID: UUID
    let name: String
    let displayAmount: String
    let displayRunningBalance: String
    let memo: String
    let warningState: BalanceWarningState
    let isAutoGenerated: Bool
    let flowType: FlowType

    var id: UUID { planID }
}
