import Foundation
import Observation

@Observable
final class PlanListViewModel {
    var targetMonth: Date
    var searchText = ""
    var sections: [PlanListSection] = []
    var editingPlan: TransactionPlan?
    var isShowingEditor = false
    var deletingPlan: TransactionPlan?

    private let calendar: Calendar

    init(targetMonth: Date = .now, calendar: Calendar = .current) {
        self.targetMonth = calendar.startOfMonth(for: targetMonth)
        self.calendar = calendar
    }

    /// 前月へ移動する。
    func showPreviousMonth() {
        targetMonth = calendar.date(byAdding: .month, value: -1, to: targetMonth) ?? targetMonth
    }

    /// 翌月へ移動する。
    func showNextMonth() {
        targetMonth = calendar.date(byAdding: .month, value: 1, to: targetMonth) ?? targetMonth
    }

    /// 新規作成シートを開く。
    func presentCreate() {
        editingPlan = nil
        isShowingEditor = true
    }

    /// 編集シートを開く。
    func presentEdit(for plan: TransactionPlan) {
        editingPlan = plan
        isShowingEditor = true
    }

    /// 予定一覧を表示用セクションへ変換する。
    func reload(
        plans: [TransactionPlan],
        initialBalance: Int,
        warningThreshold: Int
    ) {
        let calculator = BalanceCalculator(calendar: calendar)
        let calculation = calculator.calculate(
            initialBalance: initialBalance,
            plans: plans,
            warningThreshold: warningThreshold
        )
        let runningBalanceMap = Dictionary(
            uniqueKeysWithValues: calculation.entries.map { entry in
                (entry.planID, entry.runningBalance)
            }
        )

        let filteredPlans = plans.filter { plan in
            calendar.isDate(plan.date, equalTo: targetMonth, toGranularity: .month)
                && matchesSearchText(plan.name)
        }

        let groupedPlans = Dictionary(grouping: filteredPlans) { plan in
            calendar.startOfDay(for: plan.date)
        }

        sections = groupedPlans.keys.sorted().map { date in
            let plansForDate = groupedPlans[date] ?? []
            let rows = plansForDate.map { plan in
                let runningBalance = runningBalanceMap[plan.id] ?? initialBalance
                return PlanListRowModel(
                    planID: plan.id,
                    name: plan.name,
                    displayAmount: CurrencyFormatter.signedString(from: plan.signedAmount),
                    displayRunningBalance: CurrencyFormatter.string(from: runningBalance),
                    memo: plan.memo,
                    warningState: .from(balance: runningBalance, warningThreshold: warningThreshold),
                    isAutoGenerated: plan.isAutoGenerated,
                    flowType: plan.flowType
                )
            }
            let incomeTotal = plansForDate
                .filter { $0.flowType == .income }
                .reduce(0) { $0 + $1.amount }
            let expenseTotal = plansForDate
                .filter { $0.flowType == .expense }
                .reduce(0) { $0 + $1.amount }

            return PlanListSection(
                date: date,
                rows: rows,
                dailyIncomeTotal: incomeTotal,
                dailyExpenseTotal: expenseTotal
            )
        }
    }

    /// 名称の部分一致検索に一致するか判定する。
    private func matchesSearchText(_ name: String) -> Bool {
        let trimmedSearchText = searchText.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmedSearchText.isEmpty == false else {
            return true
        }
        return name.localizedCaseInsensitiveContains(trimmedSearchText)
    }
}
