import Foundation
import SwiftData
import Testing
@testable import MoneyPlan

@MainActor
struct RecurringPlanGeneratorTests {
    private let calendar = Calendar(identifier: .gregorian)

    /// 停止中や範囲外のテンプレートを除いて自動生成する。
    @Test func generatesOnlyEligiblePlans() throws {
        let container = try makeContainer()
        let context = ModelContext(container)
        let generator = RecurringPlanGenerator(calendar: calendar)
        let activePlan = RecurringPlan(
            flowType: .income,
            name: "給与",
            amount: 250_000,
            dayOfMonth: 25,
            startMonth: makeMonth(3),
            endMonth: makeMonth(4)
        )
        let inactivePlan = RecurringPlan(
            flowType: .expense,
            name: "停止中",
            amount: 10_000,
            dayOfMonth: 5,
            startMonth: makeMonth(3),
            isActive: false
        )

        context.insert(activePlan)
        context.insert(inactivePlan)
        try context.save()

        try generator.syncFuturePlans(
            templates: [activePlan, inactivePlan],
            in: context,
            generationStartMonth: makeMonth(3),
            generationMonthCount: 3
        )

        let plans = try fetchGeneratedPlans(in: context)
        #expect(plans.count == 2)
        #expect(plans.map(\.name) == ["給与", "給与"])
        #expect(plans.map { calendar.component(.month, from: $0.date) } == [3, 4])
    }

    /// ロック済み自動生成予定は上書きせず保持する。
    @Test func keepsLockedGeneratedPlan() throws {
        let container = try makeContainer()
        let context = ModelContext(container)
        let generator = RecurringPlanGenerator(calendar: calendar)
        let template = RecurringPlan(
            flowType: .expense,
            name: "家賃",
            amount: 80_000,
            dayOfMonth: 27,
            startMonth: makeMonth(3)
        )
        let lockedPlan = TransactionPlan(
            date: makeDate(year: 2026, month: 3, day: 27),
            flowType: .expense,
            name: "特別家賃",
            amount: 75_000,
            memo: "手動調整",
            sortOrder: 3,
            sourceTemplateID: template.id,
            isAutoGenerated: true,
            isOccurrenceLocked: true
        )

        context.insert(template)
        context.insert(lockedPlan)
        try context.save()

        try generator.syncFuturePlans(
            templates: [template],
            in: context,
            generationStartMonth: makeMonth(3),
            generationMonthCount: 1
        )

        let plans = try fetchGeneratedPlans(in: context)
        #expect(plans.count == 1)
        #expect(plans[0].name == "特別家賃")
        #expect(plans[0].amount == 75_000)
        #expect(plans[0].memo == "手動調整")
    }

    /// 範囲外になった未ロック自動生成予定は削除する。
    @Test func deletesOutOfRangeUnlockedPlans() throws {
        let container = try makeContainer()
        let context = ModelContext(container)
        let generator = RecurringPlanGenerator(calendar: calendar)
        let template = RecurringPlan(
            flowType: .income,
            name: "副収入",
            amount: 10_000,
            dayOfMonth: 15,
            startMonth: makeMonth(3),
            endMonth: makeMonth(3)
        )
        let futureGeneratedPlan = TransactionPlan(
            date: makeDate(year: 2026, month: 4, day: 15),
            flowType: .income,
            name: "副収入",
            amount: 10_000,
            sourceTemplateID: template.id,
            isAutoGenerated: true
        )

        context.insert(template)
        context.insert(futureGeneratedPlan)
        try context.save()

        try generator.syncFuturePlans(
            templates: [template],
            in: context,
            generationStartMonth: makeMonth(3),
            generationMonthCount: 2
        )

        let plans = try fetchGeneratedPlans(in: context)
        #expect(plans.count == 1)
        #expect(calendar.component(.month, from: plans[0].date) == 3)
    }

    /// テスト用のインメモリコンテナを作る。
    private func makeContainer() throws -> ModelContainer {
        let schema = Schema([
            TransactionPlan.self,
            RecurringPlan.self,
            AppSetting.self,
        ])
        let configuration = ModelConfiguration(schema: schema, isStoredInMemoryOnly: true)
        return try ModelContainer(for: schema, configurations: [configuration])
    }

    /// 自動生成予定だけを日付順で取得する。
    private func fetchGeneratedPlans(in context: ModelContext) throws -> [TransactionPlan] {
        let descriptor = FetchDescriptor<TransactionPlan>(
            predicate: #Predicate<TransactionPlan> { plan in
                plan.isAutoGenerated
            },
            sortBy: [
                SortDescriptor(\TransactionPlan.date, order: .forward),
                SortDescriptor(\TransactionPlan.id, order: .forward),
            ]
        )
        return try context.fetch(descriptor)
    }

    /// テスト用の月初を返す。
    private func makeMonth(_ month: Int) -> Date {
        makeDate(year: 2026, month: month, day: 1)
    }

    /// テスト用の日付を返す。
    private func makeDate(year: Int, month: Int, day: Int) -> Date {
        let components = DateComponents(
            calendar: calendar,
            year: year,
            month: month,
            day: day
        )
        return components.date ?? .distantPast
    }
}
