import Foundation
import SwiftData

@MainActor
struct RecurringPlanGenerator {
    let calendar: Calendar

    init(calendar: Calendar = .current) {
        self.calendar = calendar
    }

    /// 定期予定から将来自動生成予定を同期する。
    func syncFuturePlans(
        templates: [RecurringPlan],
        in modelContext: ModelContext,
        generationStartMonth: Date,
        generationMonthCount: Int
    ) throws {
        let monthStarts = calendar.monthStarts(
            from: generationStartMonth,
            count: generationMonthCount
        )
        let validKeys = Set(buildValidOccurrenceKeys(templates: templates, monthStarts: monthStarts))
        let existingGeneratedPlans = try fetchExistingGeneratedPlans(
            from: calendar.startOfMonth(for: generationStartMonth),
            in: modelContext
        )
        var existingPlanMap: [RecurringOccurrenceKey: TransactionPlan] = [:]
        for plan in existingGeneratedPlans {
            guard let sourceTemplateID = plan.sourceTemplateID else {
                continue
            }

            let key = RecurringOccurrenceKey(
                templateID: sourceTemplateID,
                monthStart: calendar.startOfMonth(for: plan.date)
            )
            existingPlanMap[key] = plan
        }

        for existingPlan in existingGeneratedPlans {
            guard let sourceTemplateID = existingPlan.sourceTemplateID else {
                continue
            }

            let key = RecurringOccurrenceKey(
                templateID: sourceTemplateID,
                monthStart: calendar.startOfMonth(for: existingPlan.date)
            )

            if validKeys.contains(key) == false && existingPlan.isOccurrenceLocked == false {
                modelContext.delete(existingPlan)
            }
        }

        for template in templates {
            for monthStart in monthStarts {
                guard shouldGenerate(template: template, for: monthStart) else {
                    continue
                }
                guard let occurrenceDate = calendar.occurrenceDate(in: monthStart, day: template.dayOfMonth) else {
                    continue
                }

                let key = RecurringOccurrenceKey(templateID: template.id, monthStart: monthStart)

                if let existingPlan = existingPlanMap[key] {
                    if existingPlan.isOccurrenceLocked {
                        continue
                    }

                    updateGeneratedPlan(existingPlan, from: template, occurrenceDate: occurrenceDate)
                } else {
                    createGeneratedPlan(
                        from: template,
                        occurrenceDate: occurrenceDate,
                        in: modelContext
                    )
                }
            }
        }

        try modelContext.save()
    }

    /// 生成対象となる月次発生キーを作る。
    private func buildValidOccurrenceKeys(
        templates: [RecurringPlan],
        monthStarts: [Date]
    ) -> [RecurringOccurrenceKey] {
        templates.flatMap { template in
            monthStarts.compactMap { monthStart in
                guard shouldGenerate(template: template, for: monthStart) else {
                    return nil
                }
                return RecurringOccurrenceKey(templateID: template.id, monthStart: monthStart)
            }
        }
    }

    /// 生成対象月以降の自動生成予定を取得する。
    private func fetchExistingGeneratedPlans(from startDate: Date, in modelContext: ModelContext) throws -> [TransactionPlan] {
        let descriptor = FetchDescriptor<TransactionPlan>(
            predicate: #Predicate<TransactionPlan> { plan in
                plan.isAutoGenerated && plan.date >= startDate
            },
            sortBy: [
                SortDescriptor(\TransactionPlan.date, order: .forward),
                SortDescriptor(\TransactionPlan.sortOrder, order: .forward),
                SortDescriptor(\TransactionPlan.createdAt, order: .forward),
                SortDescriptor(\TransactionPlan.id, order: .forward),
            ]
        )
        return try modelContext.fetch(descriptor)
    }

    /// テンプレートが指定月に適用されるか判定する。
    private func shouldGenerate(template: RecurringPlan, for monthStart: Date) -> Bool {
        guard template.isActive else {
            return false
        }

        let normalizedStartMonth = calendar.startOfMonth(for: template.startMonth)
        if monthStart < normalizedStartMonth {
            return false
        }

        if let endMonth = template.endMonth.map({ calendar.startOfMonth(for: $0) }), monthStart > endMonth {
            return false
        }

        return true
    }

    /// 既存の自動生成予定をテンプレート内容で更新する。
    private func updateGeneratedPlan(
        _ plan: TransactionPlan,
        from template: RecurringPlan,
        occurrenceDate: Date
    ) {
        plan.date = occurrenceDate
        plan.flowType = template.flowType
        plan.name = template.name
        plan.amount = template.amount
        plan.memo = template.note
        plan.sortOrder = MoneyPlanConstants.defaultSortOrder
        plan.sourceTemplateID = template.id
        plan.isAutoGenerated = true
        plan.updatedAt = .now
    }

    /// 新しい自動生成予定を作成する。
    private func createGeneratedPlan(
        from template: RecurringPlan,
        occurrenceDate: Date,
        in modelContext: ModelContext
    ) {
        let generatedPlan = TransactionPlan(
            date: occurrenceDate,
            flowType: template.flowType,
            name: template.name,
            amount: template.amount,
            memo: template.note,
            sortOrder: MoneyPlanConstants.defaultSortOrder,
            sourceTemplateID: template.id,
            isAutoGenerated: true
        )
        modelContext.insert(generatedPlan)
    }
}

private struct RecurringOccurrenceKey: Hashable {
    let templateID: UUID
    let monthStart: Date
}
