import Foundation
import Observation
import SwiftData

@Observable
@MainActor
final class PlanEditorViewModel {
    let originalPlan: TransactionPlan?
    let recurringPlans: [RecurringPlan]

    var selectedRecurringPlanID: UUID?
    var flowType: FlowType
    var date: Date
    var name: String
    var amountText: String
    var memo: String
    var sortOrderText: String
    var validationMessage: String?
    var fieldErrors: [Field: String] = [:]
    var saveErrorMessage: String?

    enum Field {
        case name
        case amount
        case sortOrder
    }

    init(
        plan: TransactionPlan?,
        recurringPlans: [RecurringPlan],
        calendar: Calendar = .current
    ) {
        self.originalPlan = plan
        self.recurringPlans = recurringPlans
        self.flowType = plan?.flowType ?? .expense
        self.date = calendar.startOfDay(for: plan?.date ?? .now)
        self.name = plan?.name ?? ""
        self.amountText = plan.map { String($0.amount) } ?? ""
        self.memo = plan?.memo ?? ""
        self.sortOrderText = plan.map { String($0.sortOrder) } ?? String(MoneyPlanConstants.defaultSortOrder)
    }

    var navigationTitle: String {
        originalPlan == nil ? "予定を追加" : "予定を編集"
    }

    var isEditing: Bool {
        originalPlan != nil
    }

    /// 定期予定選択に応じて入力初期値を反映する。
    func applySelectedRecurringPlan() {
        guard
            let selectedRecurringPlanID,
            let recurringPlan = recurringPlans.first(where: { $0.id == selectedRecurringPlanID })
        else {
            return
        }

        flowType = recurringPlan.flowType
        name = recurringPlan.name
        amountText = String(recurringPlan.amount)
    }

    /// 入力値を検証して保存入力へ変換する。
    func makeInput() -> PlanEditorInput? {
        validationMessage = nil
        fieldErrors = [:]

        let trimmedName = name.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedMemo = memo.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedAmountText = amountText.trimmingCharacters(in: .whitespacesAndNewlines)
        let trimmedSortOrderText = sortOrderText.trimmingCharacters(in: .whitespacesAndNewlines)
        let normalizedSortOrderText = trimmedSortOrderText.isEmpty ? "0" : trimmedSortOrderText

        if trimmedName.isEmpty {
            fieldErrors[.name] = "名称を入力してください"
        }

        let amount = Int(trimmedAmountText)
        if amount == nil || (amount ?? 0) < 1 {
            fieldErrors[.amount] = "金額は 1 円以上で入力してください"
        }

        let sortOrder = Int(normalizedSortOrderText)
        if sortOrder == nil || (sortOrder ?? -1) < 0 {
            fieldErrors[.sortOrder] = "表示順は 0 以上で入力してください"
        }

        guard fieldErrors.isEmpty else {
            validationMessage = "入力内容を確認してください"
            return nil
        }

        return PlanEditorInput(
            flowType: flowType,
            date: date,
            name: trimmedName,
            amount: amount ?? 0,
            memo: trimmedMemo,
            sortOrder: sortOrder ?? 0,
            sourceTemplateID: originalPlan?.sourceTemplateID,
            isAutoGenerated: originalPlan?.isAutoGenerated ?? false
        )
    }

    /// 予定を保存する。
    func save(using modelContext: ModelContext) throws {
        saveErrorMessage = nil
        guard let input = makeInput() else {
            return
        }

        do {
            let repository = PlanRepository(modelContext: modelContext)
            _ = try repository.save(input: input, original: originalPlan)
        } catch {
            saveErrorMessage = error.localizedDescription
            throw error
        }
    }

    /// 予定を削除する。
    func delete(using modelContext: ModelContext) throws {
        guard let originalPlan else {
            return
        }

        do {
            let repository = PlanRepository(modelContext: modelContext)
            try repository.delete(originalPlan)
        } catch {
            saveErrorMessage = error.localizedDescription
            throw error
        }
    }
}
