import Foundation
import SwiftData

@Model
final class TransactionPlan {
    @Attribute(.unique) var id: UUID
    var date: Date
    var flowType: FlowType
    var name: String
    var amount: Int
    var memo: String?
    var sortOrder: Int
    var sourceTemplateID: UUID?
    var isAutoGenerated: Bool
    var isOccurrenceLocked: Bool
    var createdAt: Date
    var updatedAt: Date

    var signedAmount: Int {
        amount * flowType.signedMultiplier
    }

    init(
        id: UUID = UUID(),
        date: Date,
        flowType: FlowType,
        name: String,
        amount: Int,
        memo: String? = nil,
        sortOrder: Int = 0,
        sourceTemplateID: UUID? = nil,
        isAutoGenerated: Bool = false,
        isOccurrenceLocked: Bool = false,
        createdAt: Date = .now,
        updatedAt: Date = .now
    ) {
        self.id = id
        self.date = date
        self.flowType = flowType
        self.name = name
        self.amount = amount
        self.memo = memo
        self.sortOrder = sortOrder
        self.sourceTemplateID = sourceTemplateID
        self.isAutoGenerated = isAutoGenerated
        self.isOccurrenceLocked = isOccurrenceLocked
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}
