import Foundation
import SwiftData

struct PlanEditorInput {
    let flowType: FlowType
    let date: Date
    let name: String
    let amount: Int
    let memo: String
    let sortOrder: Int
    let sourceTemplateID: UUID?
    let isAutoGenerated: Bool
}

@MainActor
struct PlanRepository {
    let modelContext: ModelContext
    let calendar: Calendar

    init(modelContext: ModelContext, calendar: Calendar = .current) {
        self.modelContext = modelContext
        self.calendar = calendar
    }

    /// 月次一覧用の予定を取得する。
    func fetchPlans(in month: Date, searchText: String = "") throws -> [TransactionPlan] {
        let startDate = calendar.startOfMonth(for: month)
        let endDate = calendar.startOfNextMonth(for: month)
        let plans = try fetchPlans(from: startDate, to: endDate)
        let trimmedSearchText = searchText.trimmingCharacters(in: .whitespacesAndNewlines)

        guard trimmedSearchText.isEmpty == false else {
            return plans
        }

        return plans.filter { plan in
            plan.name.localizedCaseInsensitiveContains(trimmedSearchText)
        }
    }

    /// 指定期間の予定を取得する。
    func fetchPlans(from startDate: Date, to endDate: Date? = nil) throws -> [TransactionPlan] {
        let normalizedStartDate = calendar.startOfDay(for: startDate)
        let descriptor = FetchDescriptor<TransactionPlan>(
            predicate: planPredicate(from: normalizedStartDate, to: endDate),
            sortBy: planSortDescriptors()
        )
        return try modelContext.fetch(descriptor)
    }

    /// 全予定を一覧順で取得する。
    func fetchAll() throws -> [TransactionPlan] {
        let descriptor = FetchDescriptor<TransactionPlan>(sortBy: planSortDescriptors())
        return try modelContext.fetch(descriptor)
    }

    /// 指定テンプレート由来の自動生成予定を取得する。
    func fetchGeneratedPlans(sourceTemplateID: UUID) throws -> [TransactionPlan] {
        let descriptor = FetchDescriptor<TransactionPlan>(
            predicate: #Predicate<TransactionPlan> { plan in
                plan.isAutoGenerated && plan.sourceTemplateID == sourceTemplateID
            },
            sortBy: planSortDescriptors()
        )
        return try modelContext.fetch(descriptor)
    }

    /// 編集入力から予定を保存する。
    @discardableResult
    func save(input: PlanEditorInput, original: TransactionPlan? = nil) throws -> TransactionPlan {
        let plan = original ?? TransactionPlan(
            date: calendar.startOfDay(for: input.date),
            flowType: input.flowType,
            name: input.name.trimmingCharacters(in: .whitespacesAndNewlines),
            amount: input.amount,
            memo: input.memo.trimmingCharacters(in: .whitespacesAndNewlines),
            sortOrder: input.sortOrder,
            sourceTemplateID: input.sourceTemplateID,
            isAutoGenerated: input.isAutoGenerated
        )

        let didChangePrimaryFields = original.map { existing in
            existing.date != calendar.startOfDay(for: input.date)
                || existing.flowType != input.flowType
                || existing.name != input.name.trimmingCharacters(in: .whitespacesAndNewlines)
                || existing.amount != input.amount
                || existing.sortOrder != input.sortOrder
        } ?? false

        if original == nil {
            modelContext.insert(plan)
        }

        plan.date = calendar.startOfDay(for: input.date)
        plan.flowType = input.flowType
        plan.name = input.name.trimmingCharacters(in: .whitespacesAndNewlines)
        plan.amount = input.amount
        plan.memo = input.memo.trimmingCharacters(in: .whitespacesAndNewlines)
        plan.sortOrder = input.sortOrder
        plan.sourceTemplateID = input.sourceTemplateID
        plan.isAutoGenerated = input.isAutoGenerated
        if plan.isAutoGenerated && didChangePrimaryFields {
            plan.isOccurrenceLocked = true
        }
        plan.updatedAt = .now

        try modelContext.save()
        return plan
    }

    /// 指定予定を削除する。
    func delete(_ plan: TransactionPlan) throws {
        modelContext.delete(plan)
        try modelContext.save()
    }

    /// 予定一覧の安定ソート条件を返す。
    private func planSortDescriptors() -> [SortDescriptor<TransactionPlan>] {
        [
            SortDescriptor(\TransactionPlan.date, order: .forward),
            SortDescriptor(\TransactionPlan.sortOrder, order: .forward),
            SortDescriptor(\TransactionPlan.createdAt, order: .forward),
            SortDescriptor(\TransactionPlan.id, order: .forward),
        ]
    }

    /// 開始日と終了日で予定フェッチ条件を組み立てる。
    private func planPredicate(from startDate: Date, to endDate: Date?) -> Predicate<TransactionPlan> {
        if let endDate {
            return #Predicate<TransactionPlan> { plan in
                plan.date >= startDate && plan.date < endDate
            }
        }

        return #Predicate<TransactionPlan> { plan in
            plan.date >= startDate
        }
    }
}
