import Foundation

enum DashboardGraphRange: String, CaseIterable, Identifiable {
    case oneMonth
    case all

    var id: String { rawValue }

    var title: String {
        switch self {
        case .oneMonth:
            "直近1か月"
        case .all:
            "全期間"
        }
    }
}

struct BalancePoint: Identifiable {
    let id = UUID()
    let date: Date
    let balance: Int
}

struct UpcomingPlanRowModel: Identifiable {
    let planID: UUID
    let date: Date
    let name: String
    let displayAmount: String
    let memo: String
    let warningState: BalanceWarningState
    let isAutoGenerated: Bool
    let flowType: FlowType

    var id: UUID { planID }
}

struct DashboardSummary {
    let currentBalance: Int
    let monthlyIncomeTotal: Int
    let monthlyExpenseTotal: Int
    let lowestProjectedBalance: Int
    let warningState: BalanceWarningState
    let warningMessage: String
    let graphRange: DashboardGraphRange
    let graphPoints: [BalancePoint]
    let upcomingPlans: [UpcomingPlanRowModel]

    /// 表示前の空サマリーを返す。
    static func empty(
        graphRange: DashboardGraphRange,
        referenceDate: Date
    ) -> DashboardSummary {
        DashboardSummary(
            currentBalance: 0,
            monthlyIncomeTotal: 0,
            monthlyExpenseTotal: 0,
            lowestProjectedBalance: 0,
            warningState: .none,
            warningMessage: "警告はありません。",
            graphRange: graphRange,
            graphPoints: [BalancePoint(date: referenceDate, balance: 0)],
            upcomingPlans: []
        )
    }
}
